#!/bin/bash

#
# /etc/rc.d/init.d/publicdns2cname
#
# chkconfig: 345 44 56
#

start() {
	# example: U8RMOXXXXXXOPW
	HOSTED_ZONE_ID=""
	# example: ec2.example.com. Then hostname will be [sub-domain].ec2.example.com
	DOMAIN_NAME=""
	# example: 60
	TTL=60
	
	[ -z "${HOSTED_ZONE_ID}" || -z ${DOMAIN_NAME} ] && { echo "Please setup HOSTED_ZONE_ID and DOMAIN_NAME"; exit 1; }

	TAGNAME="sub-domain"
	SELF_META_URL="http://169.254.169.254/latest/meta-data"
	MY_PUBLIC_DNS=$(curl ${SELF_META_URL}/public-hostname 2>/dev/null)
	MY_INSTANCE_ID=$(curl ${SELF_META_URL}/instance-id 2>/dev/null)
	SUBDOMAIN=$(aws ec2 describe-tags --output text --query "Tags[?ResourceId==\`${MY_INSTANCE_ID}\`] | [?Key==\`${TAGNAME}\`].[Value]")
	HOSTNAME=${SUBDOMAIN}.${DOMAIN_NAME}

	#
	# Update CNAME record
	#
cat << EOT > /tmp/aws_r53_batch.json
{
"Comment": "Assign AWS Public DNS as a CNAME of hostname",
"Changes": [
	{
	"Action": "UPSERT",
	"ResourceRecordSet": {
		"Name": "${HOSTNAME}.",
		"Type": "CNAME",
		"TTL": ${TTL},
		"ResourceRecords": [
		{
			"Value": "${MY_PUBLIC_DNS}"
		}
		]
	}
	}
]
}
EOT

	aws route53 change-resource-record-sets --hosted-zone-id ${HOSTED_ZONE_ID} --change-batch file:///tmp/aws_r53_batch.json
	rm -f /tmp/aws_r53_batch.json

    return $?
}

stop()
{
    return 0
}

restart() {
    stop
    start
}

#
# Check environment
#
cat /etc/system-release | grep "Amazon Linux" > /dev/null 2>&1 || { echo "This host is not Amazon Linux"; exit 1; }
type aws > /dev/null 2>&1 || { echo "Please install awscli"; exit 1; }
[ -f ~/.aws/config ] || { echo "Please configure awscli"; exit 1; }

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        RETVAL=2
esac
exit $RETVAL

